# Generated by Django 4.0.6 on 2025-12-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_telegram', models.CharField(max_length=100)),
                ('timesstap', models.DateField(auto_now_add=True)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
