# Generated by Django 4.0.6 on 2025-12-11 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaEmpresa',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('productos', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=250)),
                ('comuna', models.CharField(max_length=150)),
                ('lat', models.IntegerField()),
                ('long', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CVUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.BinaryField()),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('palabra1', models.CharField(blank=True, max_length=200, null=True)),
                ('palabra2', models.CharField(blank=True, max_length=200, null=True)),
                ('palabra3', models.CharField(blank=True, max_length=200, null=True)),
                ('palabra4', models.CharField(blank=True, max_length=200, null=True)),
                ('palabra5', models.CharField(blank=True, max_length=200, null=True)),
                ('palabra6', models.CharField(blank=True, max_length=200, null=True)),
                ('palabra7', models.CharField(blank=True, max_length=200, null=True)),
                ('palabra8', models.CharField(blank=True, max_length=200, null=True)),
                ('palabra9', models.CharField(blank=True, max_length=200, null=True)),
                ('palabra10', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('calle', models.CharField(max_length=250)),
                ('comuna', models.CharField(max_length=150)),
                ('lat', models.IntegerField()),
                ('long', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id_etapa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id_idea', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oportunidades',
            fields=[
                ('id_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id_salida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.etapa')),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areaempresa')),
            ],
        ),
    ]
