# Generated by Django 4.0.6 on 2025-12-10 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.BinaryField()),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('palabra1', models.CharField(blank=True, max_length=50, null=True)),
                ('palabra2', models.CharField(blank=True, max_length=50, null=True)),
                ('palabra3', models.CharField(blank=True, max_length=50, null=True)),
                ('palabra4', models.CharField(blank=True, max_length=50, null=True)),
                ('palabra5', models.CharField(blank=True, max_length=50, null=True)),
                ('palabra6', models.CharField(blank=True, max_length=50, null=True)),
                ('palabra7', models.CharField(blank=True, max_length=50, null=True)),
                ('palabra8', models.CharField(blank=True, max_length=50, null=True)),
                ('palabra9', models.CharField(blank=True, max_length=50, null=True)),
                ('palabra10', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
