# Generated by Django 4.0.6 on 2025-12-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvusuario',
            name='archivo',
            field=models.TextField(),
        ),
    ]
