# Generated by Django 4.0.6 on 2025-12-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cvusuario_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvusuario',
            name='archivo',
            field=models.BinaryField(),
        ),
    ]
