# Generated by Django 4.0.6 on 2025-11-21 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_idea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='area',
        ),
        migrations.AddField(
            model_name='idea',
            name='etapa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.etapa'),
            preserve_default=False,
        ),
    ]
