# Generated by Django 4.0.6 on 2025-12-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usuario_empresa_coordinador'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_coordinador',
            field=models.BooleanField(default=False),
        ),
    ]
